version: '3'

sut:
  build: .
  command: python3 src/manage.py test
  depends_on:
  - postgres
  - backend

services:
  postgres:
    image: postgres:9.6.3
    environment:
    - POSTGRES_PASSWORD=pass
    
  backend:
    image: arihrannar/veritus-backend:latest
    environment:
    - DB_USER=postgres
    - DB_PASS=pass
    - DB_HOST=postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
