# Docker-compose file for spinning up a database service and building the backend
# This allows the CI to run our unit tests against the database
version: '2.1'

services:
  db:
    image: postgres:9.6.3
    command: psql -c "CREATE DATABASE politech;" -U postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3

  sut:
    build: .
    command: "bash -c 'python3 src/manage.py migrate && python3 src/manage.py loaddata init_data.json && python3 src/manage.py test'"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - SECRET_KEY=$SECRET_KEY
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

