# Docker-compose file for spinning up a database service and building the backend
# This allows the CI to run our unit tests against the database
version: '2.1'

services:
  db:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3

  sut:
    build: .
    command: sh .entrypoint.sh
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - SECRET_KEY=$SECRET_KEY
      - DB_HOST=db
      - ALLOWED_HOSTS=[]
      - CORS_ORIGIN_WHITELIST=()
      - GATHER_CASES_CRON_TIME_SECONDS=1440
      - DJANGO_SETTINGS_MODULE=politech_backend.settings.local
    depends_on:
      db:
        condition: service_healthy

