version: '3'

services:
  db:
    image: postgres:9.6.3
    environment:
    - POSTGRES_PASSWORD=pass
    
  sut:
    build: .
    command: python3 src/manage.py test
    environment:
    - DB_USER=postgres
    - DB_PASS=pass
    - DB_HOST=db
    #ports:
     # - "8000:8000"
    depends_on:
      - db
