version: '3'

services:
  db:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=postgres  #$POSTGRES_USER
      - POSTGRES_PASSWORD=pass #$POSTGRES_PASSWORD

  sut:
    build: .
    command: python3 src/manage.py test
    environment:
      - POSTGRES_USER=postgres #$POSTGRES_USER
      - POSTGRES_PASSWORD=pass #$POSTGRES_PASSWORD
      - DB_HOST=db
    depends_on:
      - db
    links:
      - db
