version: '3.2'

services:
  db:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'db' -U 'postgres' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3

  sut:
    build: .
    command: python3 src/manage.py test
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_HOST=db
    depends_on:
      - db
        condition: service_healthy
