version: '3'

services:
  db:
    image: postgres:latest

  backend:
    build: .
    environment:
    - DB_USER=postgres
    - DB_PASS=pass
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db