version: '2.1'

services:
  db:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kaninei3i3j94jginerign
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3
    
  backend:
    image: veritus/backend:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kaninei3i3j94jginerign
      - SECRET_KEY=nin3on3inri3nnwoge
      - DB_HOST=db
      - DEBUG=false
      - ALLOWED_HOSTS=["*"]
      - CORS_ORIGIN_WHITELIST=('localhost:3000',)
      - GATHER_CASES_CRON_TIME_SECONDS=1440
    volumes:
      - ./:/code
    command: "bash -c 'python3 src/manage.py migrate && python3 src/manage.py loaddata init_data.json && cron && cd src && gunicorn -b 0.0.0.0:8000 politech_backend.wsgi'"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  # Sentry setup
  sentry:
    image: sentry:8.17.0
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      SENTRY_SECRET_KEY: 'n1cyts8@lg(q_^sgpb!&#9=6-z&tvxp87ve&ax1p@o38@)3%r%'
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgresSentry
      SENTRY_EMAIL_HOST: smtp
    volumes:
      - ./code/sentry:/var/lib/sentry/files
  # Smtp for Sentry
  smtp:
    image: tianon/exim4
  
  # Databases for sentry
  memcached:
    image: memcached:1.4

  redis:
    image: redis:3.2-alpine

  postgresSentry:
    image: postgres:9.6.3
    volumes:
      - ./code/postgresSentry:/var/lib/postgresql/data

  web:
    extends: sentry
    links:
      - redis
      - postgresSentry
      - memcached
      - smtp
    ports:
      - '9000:9000'

  cron:
    extends: sentry
    command: run cron
    links:
      - redis
      - postgresSentry
      - memcached
      - smtp

  worker:
    extends: sentry
    command: run worker
    links:
      - redis
      - postgresSentry
      - memcached
      - smtp
