# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0002_parliamentmember'),
        ('case_gather', '0002_auto_20170428_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('supersubject_id', models.IntegerField(blank=True, null=True)),
                ('parliament_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.ParliamentSession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='number',
            new_name='subject_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='parent',
        ),
        migrations.AddField(
            model_name='subject',
            name='supersubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case_gather.SuperSubject'),
        ),
    ]
