# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0002_parliamentmember'),
        ('case_gather', '0002_auto_20170428_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='althingi_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casecreator',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_gather.Case'),
        ),
        migrations.AddField(
            model_name='casecreator',
            name='parliament_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.ParliamentMember'),
        ),
    ]
