# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_gather', '0003_auto_20170613_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_status',
            new_name='althingi_status',
        ),
        migrations.AlterField(
            model_name='casecreator',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_creators', to='case_gather.Case'),
        ),
    ]
