# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_gather', '0003_auto_20170502_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_id',
            new_name='number',
        ),
    ]
