# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_gather', '0004_auto_20170613_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlthingiStatusToStatusMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('althingi_status', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
