# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_gather', '0004_auto_20170502_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supersubject',
            old_name='supersubject_id',
            new_name='number',
        ),
    ]
