# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_gather', '0005_althingistatustostatusmapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
