# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='district',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='politicians', to='district.District'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='districtNumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='initials',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='party',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='party.Party'),
        ),
    ]
