# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='district.District'),
        ),
    ]
