# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_gather', '0002_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_date',
            field=models.DateField(null=True),
        ),
    ]
