# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_gather', '0003_bill_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='description',
            new_name='description_link',
        ),
    ]
