# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0001_initial'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('althingi_result', models.TextField()),
                ('parliament_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.ParliamentMember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
