# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-12 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_auto_20171112_1035'),
        ('votes', '0005_auto_20171112_1213'),
    ]

    operations = [
    ]
