# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-06 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_gather', '0001_initial'),
        ('promises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_gather.Case')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_gather.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='PromiseSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promises.Promise')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_gather.Subject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='promisesubject',
            unique_together=set([('promise', 'subject')]),
        ),
        migrations.AlterUniqueTogether(
            name='casesubject',
            unique_together=set([('case', 'subject')]),
        ),
    ]
