# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_gather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='major_group_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='major_group_number',
        ),
        migrations.AddField(
            model_name='subject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case_gather.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='parliament_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.ParliamentSession'),
        ),
    ]
