# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0001_initial'),
        ('case_gather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlthingiStatusToStatusMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('althingi_status', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='case',
            name='althingi_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='althingi_status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casecreator',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_creators', to='case_gather.Case'),
        ),
        migrations.AddField(
            model_name='casecreator',
            name='parliament_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.ParliamentMember'),
        ),
    ]
