# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-11 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_gather', '0003_auto_20170815_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
