# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-03 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0002_auto_20170905_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promisecase',
            old_name='percent_of_related_subjects',
            new_name='percent_of_common_subjects',
        ),
    ]
