# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-31 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0005_auto_20171003_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promisecase',
            name='relationship_type',
            field=models.CharField(
                choices=[('Connected', 'Connected'), ('Suggested', 'Suggested')], max_length=100),
        ),
    ]
