# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parliament', '0001_initial'),
        ('bill_gather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('small_description', models.TextField()),
                ('long_description', models.TextField()),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Parliament')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromiseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_gather.Bill')),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promises.Promise')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedPromiseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_gather.Bill')),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promises.Promise')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='suggestedpromisebill',
            unique_together=set([('promise', 'bill')]),
        ),
        migrations.AlterUniqueTogether(
            name='promisebill',
            unique_together=set([('promise', 'bill')]),
        ),
    ]
