# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0002_parliamentmember'),
        ('party', '0001_initial'),
        ('promises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='parliamentMember',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.ParliamentMember'),
        ),
        migrations.AddField(
            model_name='promise',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Party'),
        ),
    ]
