# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-06 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
