# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promise',
            old_name='parliament_session',
            new_name='parliament',
        ),
    ]
